name: fast_zarinpal
description: Quick implementation of Zarinpal payments with fast_zarinpal
version: 0.1.2
homepage: https://github.com/3raaj/fast_zarinpal
environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  zarinpal: ^1.0.4+1
  uni_links: ^0.5.1
  url_launcher: ^6.1.7
  persian_number_utility: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
